### ISSUE TITLE
Tweets that's disappear.

### ISSUE THREAD

**Issue by EChelicerae** [simonsarris/Twitter-Bugs#11]
This was once an old bug around 2009 where tweets would disappear that sometimes mentions specific things.

A similar bug is back again, and you're not just seemingly having tweets disappearing for mentioning things. You'll have tweets that might disappear if you delete a threaded tweet below it directly on your profile timeline.

**Comment by igorbrigadir** [comment]
A recent example that stumped me: https://twitter.com/IgorBrigadir/status/1487780777442037766 see thread here.

**Comment by simonsarris** [comment]
This seems like a policy issue, not a bug.
